class Exception {
    constructor(message) {
        this.message = message;
    }
}

var RANDOM_STRING_LENGTH = 8;

var MESSAGE_TYPE_SUCCESS_SERVER = "Success";
var MESSAGE_TYPE_FAILURE_SERVER = "Failure";
var MESSAGE_TYPE_USER_CONNECTED_SERVER = "User connected";
var MESSAGE_TYPE_CONNECTION_CLIENT = "Connection";
var MESSAGE_TYPE_USER_LIST_SERVER = "User list";
var MESSAGE_TYPE_USER_CHANGED_SERVER = "User changed";
var MESSAGE_TYPE_USER_DISCONNECTED_SERVER = "User disconnected";
var MESSAGE_TYPE_PROPOSAL_CAME_SERVER = "New proposal server";
var MESSAGE_TYPE_PROPOSAL_CAME_CLIENT = "New proposal client";
var MESSAGE_TYPE_PROPOSAL_ACCEPTED_SERVER = "Proposal accepted server";
var MESSAGE_TYPE_PROPOSAL_DECLINED_SERVER = "Proposal declined server";
var MESSAGE_TYPE_PROPOSAL_ACCEPTED_CLIENT = "Proposal accepted client";
var MESSAGE_TYPE_PROPOSAL_DECLINED_CLIENT = "Proposal declined client";
var MESSAGE_TYPE_PROPOSAL_BOB_CAME_TO_GAME_SERVER = "Proposal bob came to game";
var MESSAGE_TYPE_PROPOSAL_BOB_DISCONNECTED_SERVER = "Proposal bob disconnected";
var MESSAGE_TYPE_PROPOSAL_ALICE_BACKED_OUT_SERVER = "Proposal Alice backed out";
var MESSAGE_TYPE_PROPOSAL_ALICE_BACKED_OUT_CLIENT = "Proposal Alice backed out";
var MESSAGE_TYPE_PROPOSAL_ALICE_DISCONNECTED_SERVER = "Proposal Alice disconnected";
var MESSAGE_TYPE_PROPOSAL_ALICE_CAME_TO_GAME_SERVER = "Proposal Alice came to game";


var REASON_LOGIN_UNAVAILABLE = "Login unavailable";
var REASON_USER_NOT_FOUND = "User not found";
var REASON_PROPOSAL_NOT_FOUND = "Proposal not found";
var REASON_PROPOSAL_WHILE_USER_IN_GAME = "Proposal while user in game";

var LINE_USER_IDS = "User";

var USER_STATUS_LOBBY = "Lobby";
var USER_STATUS_GAME = "Game";

function genRandomString() {
    var text = "";
    var possible = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";

    for (var i = 0; i < RANDOM_STRING_LENGTH; i++) {
        text += possible.charAt(Math.floor(Math.random() * possible.length));
    }

    return text;
}

module.exports.genRandomString = genRandomString;

module.exports.LINE_USER_ID = LINE_USER_IDS;
module.exports.USER_STATUS_LOBBY = USER_STATUS_LOBBY;
module.exports.USER_STATUS_GAME = USER_STATUS_GAME;

module.exports.Exception = Exception;

module.exports.REASON_USER_NOT_FOUND = REASON_USER_NOT_FOUND;
module.exports.REASON_PROPOSAL_NOT_FOUND = REASON_PROPOSAL_NOT_FOUND;
module.exports.REASON_LOGIN_UNAVAILABLE = REASON_LOGIN_UNAVAILABLE;
module.exports.REASON_PROPOSAL_WHILE_USER_IN_GAME = REASON_PROPOSAL_WHILE_USER_IN_GAME


module.exports.MESSAGE_TYPE_SUCCESS_SERVER = MESSAGE_TYPE_SUCCESS_SERVER;
module.exports.MESSAGE_TYPE_FAILURE_SERVER = MESSAGE_TYPE_FAILURE_SERVER;
module.exports.MESSAGE_TYPE_USER_CONNECTED_SERVER = MESSAGE_TYPE_USER_CONNECTED_SERVER;
module.exports.MESSAGE_TYPE_CONNECTION_CLIENT = MESSAGE_TYPE_CONNECTION_CLIENT;
module.exports.MESSAGE_TYPE_USER_LIST_SERVER = MESSAGE_TYPE_USER_LIST_SERVER;
module.exports.MESSAGE_TYPE_USER_CHANGED_SERVER = MESSAGE_TYPE_USER_CHANGED_SERVER;
module.exports.MESSAGE_TYPE_USER_DISCONNECTED_SERVER = MESSAGE_TYPE_USER_DISCONNECTED_SERVER;
module.exports.MESSAGE_TYPE_PROPOSAL_CAME_SERVER = MESSAGE_TYPE_PROPOSAL_CAME_SERVER;
module.exports.MESSAGE_TYPE_PROPOSAL_CAME_CLIENT = MESSAGE_TYPE_PROPOSAL_CAME_CLIENT;
module.exports.MESSAGE_TYPE_PROPOSAL_ACCEPTED_SERVER = MESSAGE_TYPE_PROPOSAL_ACCEPTED_SERVER;
module.exports.MESSAGE_TYPE_PROPOSAL_DECLINED_SERVER = MESSAGE_TYPE_PROPOSAL_DECLINED_SERVER;
module.exports.MESSAGE_TYPE_PROPOSAL_ACCEPTED_CLIENT = MESSAGE_TYPE_PROPOSAL_ACCEPTED_CLIENT;
module.exports.MESSAGE_TYPE_PROPOSAL_DECLINED_CLIENT = MESSAGE_TYPE_PROPOSAL_DECLINED_CLIENT;
module.exports.MESSAGE_TYPE_PROPOSAL_BOB_CAME_TO_GAME_SERVER = MESSAGE_TYPE_PROPOSAL_BOB_CAME_TO_GAME_SERVER;
module.exports.MESSAGE_TYPE_PROPOSAL_BOB_DISCONNECTED_SERVER = MESSAGE_TYPE_PROPOSAL_BOB_DISCONNECTED_SERVER;
module.exports.MESSAGE_TYPE_PROPOSAL_ALICE_BACKED_OUT_SERVER = MESSAGE_TYPE_PROPOSAL_ALICE_BACKED_OUT_SERVER;
module.exports.MESSAGE_TYPE_PROPOSAL_ALICE_BACKED_OUT_CLIENT = MESSAGE_TYPE_PROPOSAL_ALICE_BACKED_OUT_CLIENT;
module.exports.MESSAGE_TYPE_PROPOSAL_ALICE_DISCONNECTED_SERVER = MESSAGE_TYPE_PROPOSAL_ALICE_DISCONNECTED_SERVER;
module.exports.MESSAGE_TYPE_PROPOSAL_ALICE_CAME_TO_GAME_SERVER = MESSAGE_TYPE_PROPOSAL_ALICE_CAME_TO_GAME_SERVER;
